spring:
  application:
    name: danafix
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver

server:
  port: 8282
  servlet:
    context-path: /danafix
